server:
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true #开启jsp的热部署
spring:
  profiles:
    active: prod  #激活测试文件
  mvc:
    view:
      prefix: /   #配置SpringBoot的视图解析器
      suffix: .jsp
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel
    username: root
    password: 123
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/Dao/*Mapper.xml
